### PR TITLE
introducing a variable called `bundesland_notes`

### PR DESCRIPTION
**Pull request by favstats**
The variable `bundesland_notes` includes notes… on individual bundesländer (if there are any).

This pull request already includes modified tests that are passing.

### CODE REVIEW

**Comment by favstats** [comment]
Oh wow, this is so much easier! :D

**Comment by friep** [comment]
@favstats thanks for the work on extracting the annotations :)!! I adapted your code to use a join approach so that in case of more annotations, they wouldn't be joined together.. i was thinking of a scenario like:


in table:
Saarland**
Hessen***


annotation:
**Keine Meldungen aus dem Saarland aufgrund technischer Schwierigkeiten
***inkl. Nachmeldungen vom ...

as far as I understood your code, Hessen would've ended up with  a `notes` entry like: "Keine Meldungen aus dem Saarland aufgrund technischer Schwierigkeiten\ninkl. Nachmeldungen vom ..." because it would've matched both 2 and 3 stars?

**Comment by friep** [comment]
@favstats haha github notifications is too quick for me :D

**Comment by friep** [comment]
btw that's the test that made me aware of the problem: 

```r

test_that("note extraction works with more than 2 notes", {
  df <- readxl::read_excel("test_data/impfmonitoring_three_notes.xlsx", sheet = 2)
  cleaned <- rki_clean_bundesland(df)
  expect_equal(dplyr::filter(cleaned, !is.na(.data$bundesland_notes)) %>% nrow, 4)
  # general note not part of notes column
  expect_equal(length(stringr::str_subset(cleaned$bundesland_notes, "in einigen Bundesländern werden nicht alle der in der Tabelle aufgeführten Indikationen einzeln ausgewiesen")), 0)
  expect_equal(length(stringr::str_subset(cleaned$bundesland_notes, "a second note")),  3)
  expect_equal(length(stringr::str_subset(cleaned$bundesland_notes, "a third note")),  1)

})
```

the second one was giving a 4 instead of 3.

**Comment by favstats** [comment]
Oh yea, that's totally an issue with string matching by stars as I had suggested. Your join approach is **much more robust**. 

> @favstats thanks for the work on extracting the annotations :)!! I adapted your code to use a join approach so that in case of more annotations, they wouldn't be joined together.. i was thinking of a scenario like:
> 
> in table:
> Saarland**
> Hessen***
> 
> annotation:
> **Keine Meldungen aus dem Saarland aufgrund technischer Schwierigkeiten
> ***inkl. Nachmeldungen vom ...
> 
> as far as I understood your code, Hessen would've ended up with a `notes` entry like: "Keine Meldungen aus dem Saarland aufgrund technischer Schwierigkeiten\ninkl. Nachmeldungen vom ..." because it would've matched both 2 and 3 stars?

**Pull request merged**
